name: Edgeserver Upload
author: Lucemans
description: Upload folder to edgeserver.io
inputs:
  server:
    description: 'URL of Edgeserver Instance'
    required: false
    default: 'api.edgeserver.io'
  site_id:
    description: 'ID of the Site to Deploy to'
    required: true
  token:
    description: 'Auth Token to Access Edgeserver'
    required: true
  directory:
    description: 'Directory to upload'
    default: 'dist'
    required: false
  context:
    description: 'Upload github action context'
    default: '1'
    required: false
runs:
  using: 'node16'
  main: 'lib/run/index.js'
  pre: 'lib/pre/index.js'
  post: 'lib/post/index.js'
branding:
  color: yellow
  icon: upload-cloud
